[book]
authors = ["Russ Cox, Frans Kaashoek, Robert Morris, and Evgeny Golyshev"]
language = "en"
multilingual = false
src = "src"
title = "xv6: a simple, Unix-like teaching operating system"

[output.html]
additional-css = ["theme/css/custom-paragraph.css"]

[output.pandoc]
optional = true

[output.pandoc.profile.pdf]
output-file = "xv6-riscv-expanded-edition.pdf"
pdf-engine = "lualatex"

[output.pandoc.profile.pdf.variables]
mainfont = "Noto Serif"
sansfont = "Noto Sans"
monofont = "Noto Sans Mono"
mainfontfallback = ["NotoColorEmoji:mode=harf"]
monofontfallback = [
  "NotoColorEmoji:mode=harf",
  "NotoSansMath:",
  "NotoSansMonoCJKSC:",
]
geometry = ["a4paper"]
header-includes = [
  "\\usepackage{pdfpages}",
  "\\AtBeginDocument{\\includepdf[pages=1,fitpaper=true,pagecommand={\\thispagestyle{empty}}]{src/cover.pdf}\\clearpage}",
  "\\setlength{\\parindent}{1.5em}",
]
